### ISSUE TITLE
Can't save work or instance with local deployment

### ISSUE THREAD

**Issue by greeve** [lcnetdev/verso#17]
We setup recto and verso locally in our library to experiment with the BIBFRAME editor to help educate both our cataloging staff and IT personnel. When we try saving a Work or Instance in the editor we get the following server error:

```
{
    "error": {
        "statusCode": 500,
        "name": "Error",
        "message": "key http://id.loc.gov/ontologies/bibframe/adminMetadata must not contain '.'",
        "stack": "Error: key http://id.loc.gov/ontologies/bibframe/adminMetadata must not contain '.'\n    at serializeInto (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:914:19)\n    at serializeObject (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at serializeObject (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:728:17)\n    at serializeObject (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:348:18)\n    at serializeInto (/srv/verso/node_modules/bson/lib/bson/parser/serializer.js:938:17)\n    at BSON.serialize (/srv/verso/node_modules/bson/lib/bson/bson.js:63:28)\n    at Query.toBin (/srv/verso/node_modules/mongodb-core/lib/connection/commands.js:143:25)\n    at serializeCommands (/srv/verso/node_modules/mongodb-core/lib/connection/pool.js:1045:43)\n    at Pool.write (/srv/verso/node_modules/mongodb-core/lib/connection/pool.js:1261:3)\n    at WireProtocol.command (/srv/verso/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:186:12)\n    at executeWrite (/srv/verso/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:301:11)\n    at WireProtocol.insert (/srv/verso/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:18:5)"
    }
}
```

Any ideas how to solve this error?

**Comment by kirkhess** [comment]
Sorry, I thought I had responded to this already - did you fix the problem? I will double check via a clean install to see if I can reproduce it & update the deployment instructions.
My suggestion is try starting verso with a clean install w/o the bfpilot.json file from the repo.

**Comment by greeve** [comment]
We didn't get this fixed. To work around it we switched to using the file-based storage since we are in a learning/experimentation mode with the editor so far. I will try a clean install without the bfpilot.json file. Thanks for the help.
